# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PhotoSorter < Formula
  desc "A TUI application for organizing photos and videos from different devices"
  homepage "https://github.com/dmitriy-dorofeev/photo-sorter"
  version "0.15.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.3/photo-sorter_0.15.3_Darwin_x86_64.tar.gz"
      sha256 "51a8833160c5b366148f68840fe34ec9609bc167628ec6635ef1f2699f2f7d89"

      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.3/photo-sorter_0.15.3_Darwin_arm64.tar.gz"
      sha256 "7d14889fee971cccec584a44f4301c1e93357ce31ccb0436f3cb080a45ca09c6"

      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.3/photo-sorter_0.15.3_Linux_x86_64.tar.gz"
      sha256 "8b7de207bda6946df921aa602c584c55cf551f14ae5f6e2827054651d5d042c1"
      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.3/photo-sorter_0.15.3_Linux_arm64.tar.gz"
      sha256 "5acde1c1e7ab3202c84eab7228270fe6b53e870f7c3df6a79954d6de262901de"
      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
  end

  test do
    system "#{bin}/photo-sorter", "--version"
  end
end
