# This file was generated by GoReleaser. DO NOT EDIT.
cask "photo-sorter" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "fa44551cda300964f57699e91e1653bd64e28c24ed687e981a4939a4cd392e2c"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "dda1d30326f408d3305f42c9f6b2ce936867304961ea6f55a7621ab70a4d22ce"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6402fa844650d0aa9cf5149fc721a1fdd15f17cf31fff10a409de82030be910b"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "723cb8a16dfcbf5e7741be141d39d930ee55b36d5845096eb3ffa32e049350ae"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "photo-sorter"
  desc "A TUI application for organizing photos and videos from different devices"
  homepage "https://github.com/dmitriy-dorofeev/photo-sorter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "photo-sorter"

  # No zap stanza required

end
