# This file was generated by GoReleaser. DO NOT EDIT.
cask "photo-sorter" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "d7b50c54010a71d5830dd246efa516d5f6e6ada61e874f72f3e0ff8371a4407e"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a8f98bf6f38a27e9bde563122b4bb12ab56169b2a967d3dcb24153ad8ed44f93"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4074cc13da96e7be3dd2e6f24005eb97d02e350d0de88d3cfb81c600e8dd4a68"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1d188e5e65945e62cd306ea110604abce42faa3513212639dfdbc69af4638e8b"
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v#{version}/photo-sorter_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "photo-sorter"
  desc "A TUI application for organizing photos and videos from different devices"
  homepage "https://github.com/dmitriy-dorofeev/photo-sorter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "photo-sorter"

  # No zap stanza required

end
