# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PhotoSorter < Formula
  desc "A TUI application for organizing photos and videos from different devices"
  homepage "https://github.com/dmitriy-dorofeev/photo-sorter"
  version "0.15.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.4/photo-sorter_0.15.4_Darwin_x86_64.tar.gz"
      sha256 "c4bd143ff50813a5b0f403c0d3c9a446f1985ae35bbd25cb3aadc8b2c25a37ba"

      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.4/photo-sorter_0.15.4_Darwin_arm64.tar.gz"
      sha256 "f78268b8397bbad30cf8630ddf15b83f58fc385b2566ef3a94fc10cc5eb1a3e8"

      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.4/photo-sorter_0.15.4_Linux_x86_64.tar.gz"
      sha256 "dfcb20377f535939c4c22d300eeb485ba54d19b381e73be2e45ae04971af670a"
      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.15.4/photo-sorter_0.15.4_Linux_arm64.tar.gz"
      sha256 "672acdfbbf7d6b0d3c4820df4a7208349f74a73a041cf5bc989a4e4b4d60a9e6"
      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
  end

  test do
    system "#{bin}/photo-sorter", "--version"
  end
end
