# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PhotoSorter < Formula
  desc "A TUI application for organizing photos and videos from different devices"
  homepage "https://github.com/dmitriy-dorofeev/photo-sorter"
  version "0.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.14.0/photo-sorter_0.14.0_Darwin_x86_64.tar.gz"
      sha256 "55f68cfc99cabd599b3c56d7802117be5c1a191b1b01ce9731d8124660b3522d"

      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.14.0/photo-sorter_0.14.0_Darwin_arm64.tar.gz"
      sha256 "7c106f99808290ad6a333ccf3c44235710c4bd0f0862e8161a9fab137240104c"

      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.14.0/photo-sorter_0.14.0_Linux_x86_64.tar.gz"
      sha256 "1da4f3d393f889ab6bde5303826ec003a6b886595e19cd000e1e7ebf21b3c785"
      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/photo-sorter/releases/download/v0.14.0/photo-sorter_0.14.0_Linux_arm64.tar.gz"
      sha256 "36fc4e5124c29b40ca5b2c1e1ba88fad71a482b8bdf8056d71a1dc652561d19f"
      define_method(:install) do
        bin.install "photo-sorter"
      end
    end
  end

  test do
    system "#{bin}/photo-sorter", "--version"
  end
end
