# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tidysnap < Formula
  desc "A macOS utility with a TUI interface for automatic cleanup of screenshots and screen recordings."
  homepage "https://github.com/dmitriy-dorofeev/tidysnap"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.3.1/tidysnap_1.3.1_Darwin_x86_64.tar.gz"
      sha256 "71b94e75d00ab9adf182029486b481e8c52a5fab0a27f86eb59718ba50b4d2e8"

      define_method(:install) do
        bin.install "tidysnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.3.1/tidysnap_1.3.1_Darwin_arm64.tar.gz"
      sha256 "2479795825e033be1418d1a877c1d1266aa2ec1952caf1431b2985bab563c437"

      define_method(:install) do
        bin.install "tidysnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.3.1/tidysnap_1.3.1_Linux_x86_64.tar.gz"
      sha256 "58509d4efcea98910509c7a36f6e070457872eefb13094ad85e6b7f8cae34183"
      define_method(:install) do
        bin.install "tidysnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.3.1/tidysnap_1.3.1_Linux_arm64.tar.gz"
      sha256 "d810e0ee2d5284c218a3fe92176f3a6974c29e24a523a9d7515f51870b410f6b"
      define_method(:install) do
        bin.install "tidysnap"
      end
    end
  end

  test do
    system "#{bin}/tidysnap", "--version"
  end
end
