# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tidysnap < Formula
  desc "A macOS utility with a TUI interface for automatic cleanup of screenshots and screen recordings."
  homepage "https://github.com/dmitriy-dorofeev/tidysnap"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.2.0/tidysnap_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "a57d66a9a61f879f61fad9b4770fecc1d30c529820b74f04ed62d55daa56d473"

      define_method(:install) do
        bin.install "tidysnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.2.0/tidysnap_1.2.0_Darwin_arm64.tar.gz"
      sha256 "2d8df07608435bb6947b7a0917f85413dfaad749f629007b9a5a4860363ba13f"

      define_method(:install) do
        bin.install "tidysnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.2.0/tidysnap_1.2.0_Linux_x86_64.tar.gz"
      sha256 "a0ae834add1a5517664c461d334915b6c8821995adaf53214b11aca0a177d8aa"
      define_method(:install) do
        bin.install "tidysnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmitriy-dorofeev/tidysnap/releases/download/v1.2.0/tidysnap_1.2.0_Linux_arm64.tar.gz"
      sha256 "d75d71e204382ed8f7dbe4d305da6509cc5cfe1c7615a11ae4ae2d592f44ccae"
      define_method(:install) do
        bin.install "tidysnap"
      end
    end
  end

  test do
    system "#{bin}/tidysnap", "--version"
  end
end
